import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,browserLocalPersistence,setPersistence,signInWithPopup,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFirestore,doc,getDoc} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
const config=window.TAXI_PAY_FIREBASE_CONFIG||{}; const app=initializeApp(config); const auth=getAuth(app); const db=getFirestore(app); const provider=new GoogleAuthProvider();
const gate=document.getElementById('systemInfoAuthGate'),check=document.getElementById('authCheckingPanel'),status=document.getElementById('systemInfoStatus');
function showGate(msg='管理者のGoogleアカウントでログインしてください。'){document.body.classList.remove('auth-checking');check.hidden=true;gate.hidden=false;document.getElementById('systemInfoMessage').textContent=msg;}
function showPage(){document.body.classList.remove('auth-checking');check.hidden=true;gate.hidden=true;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function render(){const meta=window.TAXI_PAY_APP_META||{}; let reg=null; try{reg=await navigator.serviceWorker?.getRegistration?.();}catch{}; let cachesList=[];try{cachesList=await caches.keys();}catch{};
 const rows=[['Version',meta.version],['Build',meta.build],['Environment',meta.environment],['公開日時',meta.releasedAtJst],['Cache Version',meta.cacheVersion],['Service Worker',reg?.active?.scriptURL||'未登録'],['Service Worker状態',reg?.active?.state||'—'],['Firebase projectId',config.projectId||'—'],['現在URL',location.href],['ブラウザ',navigator.userAgent],['PWA起動',matchMedia('(display-mode: standalone)').matches||navigator.standalone===true?'はい':'いいえ']];
 document.getElementById('systemInfoList').innerHTML=rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v||'—')}</dd></div>`).join(''); document.getElementById('cacheList').innerHTML=cachesList.length?cachesList.map(x=>`<p><code>${esc(x)}</code></p>`).join(''):'<p>キャッシュはありません。</p>';}
document.getElementById('systemInfoLogin').addEventListener('click',async()=>{try{await setPersistence(auth,browserLocalPersistence);await signInWithPopup(auth,provider);}catch(e){showGate(e.message);}});document.getElementById('systemInfoLogout').addEventListener('click',()=>signOut(auth));document.getElementById('refreshSystemInfo').addEventListener('click',render);document.getElementById('rebuildPwaCache').addEventListener('click',async()=>{status.textContent='キャッシュを再構築しています…';await window.TaxiPayPhase75.recover();});
onAuthStateChanged(auth,async user=>{if(!user){showGate();return;}const s=await getDoc(doc(db,'admins',user.uid));if(!s.exists()||s.data().enabled===false){await signOut(auth);showGate('管理者権限がありません。');return;}showPage();render();});
